pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.regulaforensics.com/RegulaDocumentReader")
        }
        maven { url = uri("https://raw.githubusercontent.com/iProov/android/master/maven/") }
        maven { url = uri("https://raw.githubusercontent.com/iProov/android/beta/maven/") }
    }
}
rootProject.name = "BackendProcessing"
include ':app'
